{% set name = "quantum-blackbird" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantum-blackbird-{{ version }}.tar.gz
  sha256: 065c73bf5263ce8f9b72dcd2b434f3bfbb471f0a6907c97a617ec0c8bde01db3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - antlr-python-runtime ==4.9.2
    # Actual name is antlr4-python3-runtime but conda-forge name was different until 4.9.3
    - networkx
    - numpy >=1.16
    - python >=3.6
    - sympy

test:
  imports:
    - blackbird
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XanaduAI/blackbird
  summary: Blackbird is a quantum assembly language for continuous-variable quantum computation by Xanadu Inc.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://quantum-blackbird.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
